sudo: required

# Enable C++ support
language: 
  - C++

# Compiler selection
compiler:
  - gcc

dist: bionic

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libboost-filesystem-dev

before_install:
  - sudo apt-cache search libboost
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev	
# - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
#  - sudo tar xzvf boost_1_64_0.tar.gz
# - chmod +x installMPG123.sh
# - ./installMPG123.sh
  - chmod ugo+x script/run-tests.sh
  
install:
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"
  - echo "Ben, why you leave us hanging"

  
# Build steps
script:
  - mkdir build
  - cd build
#  - ${DEPS_DIR}/cmake/bin/cmake .. && make
# - ${DEPS_DIR}/cmake/bin/cmake .. && make
  - echo Building all the thingss
  - echo ${DEPS_DIR}
  - cd ${TRAVIS_BUILD_DIR} 
#  - "bash -c ./script/run-tests.sh" 
#  - ./home/travis/build/chunyulok/Travis_beginners/script/run-tests.sh