sudo: required
dist: bionic
before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-cache search libboost
#  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
#  - sudo tar xzvf boost_1_64_0.tar.gz
# - chmod +x installMPG123.sh
# - ./installMPG123.sh
  - chmod ugo+x script/run-tests.sh
  
# Enable C++ support
language: 
  - C++
# Compiler selection
compiler:
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - bundle install
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      #CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      $ pacman -S mingw64/mingw-w64-x86_64-cmake	
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  - cd ..
# Build steps
script:
  - mkdir build
  - cd build
#  - ${DEPS_DIR}/cmake/bin/cmake .. && make
# - ${DEPS_DIR}/cmake/bin/cmake .. && make
  - echo Building all the thingss
  - echo ${DEPS_DIR}
  - cd ${TRAVIS_BUILD_DIR} 
  - ./script/run-tests.sh 
#  - ./home/travis/build/chunyulok/Travis_beginners/script/run-tests.sh